
BiocManager::install("scran")
library(crayon);library(scran)
install.packages('Seurat')
library(Seurat)
devtools::install_github('chris-mcginnis-ucsf/MULTI-seq')
library(deMULTIplex)
library(limma)
library(DescTools)
library(ggpubr)
library(grid)
library(gridExtra)
library(reshape2)
library(scales)
library(ShortRead)
library(stringr)
library(stringdist)
library(vegan)
library(plotly)
library(plyr)
library(pheatmap)
library(easyGgplot2)
library(calibrate)
library(org.Mm.eg.db)
library(BAMMtools)
library(ggrepel)
library(xlsx)

